# Generated by Django 2.1.3 on 2018-11-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ManyToManyField(blank=True, to='tree.Photo', verbose_name='Fotos'),
        ),
    ]
