# Generated by Django 2.1.3 on 2018-11-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181126_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='reports', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'foto de reporte',
                'verbose_name_plural': 'fotos de reportes',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ManyToManyField(blank=True, to='reports.PhotoReport', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Árbol reportado'),
        ),
    ]
