# Generated by Django 2.1.3 on 2018-11-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20181126_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photos',
        ),
        migrations.AddField(
            model_name='photoreport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='Fotos'),
        ),
    ]
