# Generated by Django 2.1.3 on 2018-11-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20181126_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='Reporte asociado'),
        ),
    ]
