# Generated by Django 2.2.2 on 2019-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20181129_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('characteristic', models.TextField(blank=True, verbose_name='Caracteristica')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'amenaza',
                'verbose_name_plural': 'amenazas',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.TextField(blank=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uploaded_by',
            field=models.TextField(max_length=100, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='report',
            name='hazard',
            field=models.ManyToManyField(blank=True, to='reports.Hazard', verbose_name='Amenazas'),
        ),
    ]
