# Generated by Django 2.2.2 on 2019-06-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190630_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='active',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
