# Generated by Django 2.2.2 on 2019-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190630_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other',
            field=models.BooleanField(default=0),
        ),
    ]
