# Generated by Django 2.1.2 on 2018-10-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('reason', models.TextField(verbose_name='Razón de')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Benefict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('characteristic', models.TextField(blank=True, verbose_name='Caracteristica')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'rama',
                'verbose_name_plural': 'ramas',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'flor',
                'verbose_name_plural': 'flores',
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'habitat',
                'verbose_name_plural': 'habitats',
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('characteristic', models.TextField(blank=True, verbose_name='Caracteristica')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'amenaza',
                'verbose_name_plural': 'amenazas',
            },
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'hoja',
                'verbose_name_plural': 'hojas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='trees', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'foto de árbol',
                'verbose_name_plural': 'fotos de árboles',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'raíz',
                'verbose_name_plural': 'raices',
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': 'especies',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Altura en centimetros')),
                ('grounded', models.DateTimeField(verbose_name='Fecha de plantación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'árbol',
                'verbose_name_plural': 'árboles',
            },
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'tronco',
                'verbose_name_plural': 'troncos',
            },
        ),
        migrations.CreateModel(
            name='TypeTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('scientific_name', models.CharField(max_length=250, verbose_name='Nombre cientifico')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('family', models.CharField(max_length=100, verbose_name='Familia')),
                ('order', models.CharField(max_length=100, verbose_name='Orden')),
                ('clase', models.CharField(max_length=100, verbose_name='Clase')),
                ('subclass', models.CharField(max_length=100, verbose_name='Subclase')),
                ('origin', models.TextField(verbose_name='Origen')),
                ('preservation', models.TextField(verbose_name='Preservación')),
                ('bark_color', models.CharField(max_length=50, verbose_name='Color de corteza')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Branch', verbose_name='Rama')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Flower', verbose_name='Flor')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Habitat', verbose_name='Habitat')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Leaf', verbose_name='Hoja')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Root', verbose_name='Raiz')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Specie', verbose_name='Especie')),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Trunk', verbose_name='Tronco')),
            ],
            options={
                'verbose_name': 'árbol',
                'verbose_name_plural': 'árboles',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree')),
            ],
            options={
                'verbose_name': 'riego',
                'verbose_name_plural': 'riegos',
            },
        ),
        migrations.AddField(
            model_name='tree',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.TypeTree', verbose_name='Tipo de Árbol'),
        ),
        migrations.AddField(
            model_name='state',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Árbol asociado'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Foto de Árbol'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree'),
        ),
        migrations.AddField(
            model_name='benefict',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.TypeTree'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Árbol manipulado'),
        ),
    ]
