# Generated by Django 2.1.2 on 2018-10-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Altura en centimetros aproximada'),
        ),
    ]
