# Generated by Django 2.1.2 on 2018-10-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20181014_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefict',
            name='tree',
        ),
        migrations.AddField(
            model_name='benefict',
            name='tree',
            field=models.ManyToManyField(to='tree.TypeTree', verbose_name='Árboles con beneficios'),
        ),
    ]
