# Generated by Django 2.1.2 on 2018-10-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20181014_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetree',
            options={'verbose_name': 'tipo de árbol', 'verbose_name_plural': 'tipos de árboles'},
        ),
        migrations.RemoveField(
            model_name='benefict',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='hazard',
            name='tree',
        ),
        migrations.AddField(
            model_name='tree',
            name='hazard',
            field=models.ManyToManyField(to='tree.Hazard', verbose_name='Amenazas'),
        ),
        migrations.AddField(
            model_name='typetree',
            name='benefict',
            field=models.ManyToManyField(to='tree.Benefict', verbose_name='Árboles con beneficios'),
        ),
    ]
