# Generated by Django 2.1.2 on 2018-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20181015_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='hazard',
            field=models.ManyToManyField(blank=True, null=True, to='tree.Hazard', verbose_name='Amenazas'),
        ),
    ]
