# Generated by Django 2.1.2 on 2018-10-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20181015_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='circumference',
            field=models.PositiveIntegerField(default=1, verbose_name='Circunferencia en centimetros'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Altura en metros aproximada'),
        ),
    ]
