# Generated by Django 2.1.2 on 2018-10-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20181018_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tree',
        ),
        migrations.AddField(
            model_name='tree',
            name='images',
            field=models.ManyToManyField(blank=True, to='tree.Photo', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Longitud'),
        ),
    ]
