# Generated by Django 2.1.2 on 2018-10-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20181019_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='images',
        ),
        migrations.AddField(
            model_name='photo',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Foto de Árbol'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud'),
        ),
    ]
