# Generated by Django 2.1.7 on 2019-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20181019_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='circumference',
            field=models.PositiveIntegerField(blank=True, verbose_name='Circunferencia en centimetros'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='grounded',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de plantación'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='bark_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color de corteza'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='benefict',
            field=models.ManyToManyField(blank=True, to='tree.Benefict', verbose_name='Árboles con beneficios'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='branch',
        ),
        migrations.AddField(
            model_name='typetree',
            name='branch',
            field=models.ManyToManyField(blank=True, to='tree.Branch', verbose_name='Rama'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='clase',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='family',
            field=models.CharField(blank=True, max_length=100, verbose_name='Familia'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='flower',
        ),
        migrations.AddField(
            model_name='typetree',
            name='flower',
            field=models.ManyToManyField(blank=True, to='tree.Flower', verbose_name='Flor'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='habitat',
        ),
        migrations.AddField(
            model_name='typetree',
            name='habitat',
            field=models.ManyToManyField(blank=True, to='tree.Habitat', verbose_name='Habitat'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='leaf',
        ),
        migrations.AddField(
            model_name='typetree',
            name='leaf',
            field=models.ManyToManyField(blank=True, to='tree.Leaf', verbose_name='Hoja'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='order',
            field=models.CharField(blank=True, max_length=100, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='origin',
            field=models.TextField(blank=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='preservation',
            field=models.TextField(blank=True, verbose_name='Preservación'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='root',
        ),
        migrations.AddField(
            model_name='typetree',
            name='root',
            field=models.ManyToManyField(blank=True, to='tree.Root', verbose_name='Raiz'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nombre cientifico'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='specie',
        ),
        migrations.AddField(
            model_name='typetree',
            name='specie',
            field=models.ManyToManyField(blank=True, to='tree.Specie', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='typetree',
            name='subclass',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subclase'),
        ),
        migrations.RemoveField(
            model_name='typetree',
            name='trunk',
        ),
        migrations.AddField(
            model_name='typetree',
            name='trunk',
            field=models.ManyToManyField(blank=True, to='tree.Trunk', verbose_name='Tronco'),
        ),
    ]
