# Generated by Django 2.2.2 on 2019-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_auto_20190404_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='grounded',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='hazard',
        ),
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.TextField(blank=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Altura en cm aproximada'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de mantención'),
        ),
    ]
